### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by erelsgl** [PrefLib/PrefLib-Tools#5]
I am now working on papers related to preferences, and I will be happy to contribute some code to Pref-Lib. 
This may include both documentation&testing for existing code, and some new functionality.
Are you interested in pull requests?
If so, should I start working on the develop branch or on the master branch?

**Comment by nmattei** [comment]
Hi Erel -- I am of course interested in pull requests ;-)  The best may be to work on the Dev branch -- I was in the middle of reworking how the profiles etc. are handled internally but I have not had time to work in while with the move back to the US and all.  Please let me know if you have any questions!
